title: FinOps for POs
description: Cloud cost and invoice intelligence for Product Owners.
url: "https://knowjoby.github.io"
baseurl: ""
future: true
permalink: /:year/:month/:day/:title/
exclude:
  - state/
  - Gemfile
  - Gemfile.lock
  - .setup-complete
  - run-daily.sh
  - _drafts/
